In [7]:
import pandas as pd

In [8]:
df=pd.read_csv("C:/Users/sai/Desktop/nanis/housing.csv")

In [9]:
print(df.head(n=1))  
#prints only first record

   lotsize  bedrooms  bathrms  stories  driveway  recroom  fullbase  gashw  \
0     5850         3        1        2         1        0         1      0

   airco  garagepl  prefarea  price
0      0         1         0  42000

In [10]:
print(df.head())
#prints first five records

   lotsize  bedrooms  bathrms  stories  driveway  recroom  fullbase  gashw  \
0     5850         3        1        2         1        0         1      0
1     4000         2        1        1         1        0         0      0
2     3060         3        1        1         1        0         0      0
3     6650         3        1        2         1        1         0      0
4     6360         2        1        1         1        0         0      0

   airco  garagepl  prefarea  price
0      0         1         0  42000
1      0         0         0  38500
2      0         0         0  49500
3      0         0         0  60500
4      0         0         0  61000

In [11]:
print(df['lotsize'].mean())
#prints the total mean of lotsize column

5150.2655677655675

In [12]:
print(df['bedrooms'].median())
#prints the median of bedrooms column

3.0

In [13]:
print(df['lotsize'].std())
#prints the standard variation of lotsize column

2168.1587252285567

In [14]:
print(df['bedrooms'].head(50).mean())
#prints mean of first fifty bedrooms columns

2.72

In [15]:
df_sample=df.groupby(['lotsize'])
print(df_sample.mean())
#groups the data in the lotsize column

         bedrooms   bathrms   stories  driveway  recroom  fullbase  gashw  \
lotsize
1650     3.000000  1.000000  2.000000       0.0     0.00  1.000000    0.0
1700     3.000000  1.000000  2.000000       1.0     0.00  0.000000    0.0
1836     2.000000  1.000000  1.000000       0.0     0.00  1.000000    0.0
1905     5.000000  1.000000  2.000000       0.0     0.00  1.000000    0.0
1950     3.000000  1.500000  1.500000       0.5     0.00  0.500000    0.5
2000     2.000000  1.000000  2.000000       1.0     0.00  0.000000    0.0
2015     3.000000  1.000000  2.000000       1.0     0.00  1.000000    0.0
2135     3.000000  2.000000  2.000000       0.0     0.00  0.000000    0.0
2145     3.166667  1.166667  2.333333       1.0     0.00  0.500000    0.0
2160     3.000000  1.000000  2.000000       0.0     0.00  1.000000    0.0
2175     3.000000  1.000000  2.000000       0.0     1.00  1.000000    0.0
2176     2.000000  1.000000  2.000000       1.0     1.00  0.000000    0.0
2275     3.000000  1.000000  3.000000       1.0     0.00  0.000000    1.0
2325     3.000000  1.000000  2.000000       0.0     0.00  0.000000    0.0
2398     3.000000  1.000000  1.000000       1.0     0.00  0.000000    0.0
2400     3.000000  1.000000  1.500000       0.5     0.00  0.000000    0.0
2430     3.000000  1.000000  1.000000       0.0     0.00  0.000000    0.0
2475     3.000000  1.000000  2.000000       1.0     0.00  0.000000    0.0
2500     2.000000  1.000000  1.000000       0.0     0.00  0.000000    0.0
2520     5.000000  2.000000  1.000000       0.0     0.00  1.000000    0.0
2550     3.000000  1.000000  2.000000       1.0     0.00  1.000000    0.0
2610     3.500000  2.000000  2.000000       0.5     0.00  0.500000    0.0
2640     2.000000  1.000000  1.000000       0.0     0.00  0.000000    0.0
2650     3.000000  1.000000  2.000000       1.0     0.00  1.000000    0.0
2684     2.000000  1.000000  1.000000       1.0     0.00  0.000000    0.0
2700     2.500000  1.000000  1.000000       0.0     0.00  0.000000    0.0
2747     4.000000  2.000000  2.000000       0.0     0.00  0.000000    0.0
2787     3.500000  1.500000  1.500000       1.0     0.00  0.500000    0.0
2800     3.000000  1.500000  1.500000       0.5     0.00  0.500000    0.0
2817     4.000000  2.000000  2.000000       0.0     1.00  1.000000    0.0
...           ...       ...       ...       ...      ...       ...    ...
8500     3.000000  2.000000  4.000000       1.0     0.00  0.000000    0.0
8520     3.000000  1.000000  1.000000       1.0     0.00  0.000000    0.0
8580     4.500000  3.000000  3.000000       1.0     0.00  0.000000    0.0
8800     3.000000  2.000000  2.000000       1.0     0.00  0.000000    0.0
8875     3.000000  1.000000  1.000000       1.0     0.00  0.000000    0.0
8880     2.500000  1.500000  1.500000       1.0     0.00  0.500000    0.0
8960     4.000000  4.000000  4.000000       1.0     0.00  0.000000    0.0
9000     3.500000  1.500000  2.750000       1.0     0.25  0.250000    0.0
9166     2.000000  1.000000  1.000000       1.0     0.00  1.000000    0.0
9500     3.000000  1.000000  2.000000       1.0     0.00  0.000000    0.0
9620     3.000000  1.000000  1.000000       1.0     0.00  1.000000    0.0
9667     4.000000  2.000000  2.000000       1.0     1.00  1.000000    0.0
9800     4.000000  2.000000  2.000000       1.0     1.00  0.000000    0.0
9860     3.000000  1.000000  1.000000       1.0     0.00  0.000000    0.0
9960     3.000000  2.000000  2.000000       1.0     0.00  1.000000    0.0
10240    2.000000  1.000000  1.000000       1.0     0.00  0.000000    0.0
10269    3.000000  1.000000  1.000000       1.0     0.00  0.000000    0.0
10360    2.000000  1.000000  1.000000       1.0     0.00  0.000000    0.0
10500    3.000000  1.666667  1.333333       1.0     0.00  0.333333    0.0
10700    3.000000  1.000000  2.000000       1.0     1.00  1.000000    0.0
11175    3.000000  1.000000  1.000000       1.0     0.00  1.000000    0.0
11410    2.000000  1.000000  2.000000       1.0     0.00  0.000000    0.0
11440    4.000000  1.000000  2.000000       1.0     0.00  1.000000    0.0
11460    3.000000  1.000000  3.000000       1.0     0.00  0.000000    0.0
12090    4.000000  2.000000  2.000000       1.0     0.00  0.000000    0.0
12900    3.000000  1.000000  1.000000       1.0     0.00  0.000000    0.0
12944    3.000000  1.000000  1.000000       1.0     0.00  0.000000    0.0
13200    2.500000  1.000000  1.500000       1.0     0.00  1.000000    0.5
15600    3.000000  1.000000  1.000000       1.0     0.00  0.000000    0.0
16200    5.000000  3.000000  2.000000       1.0     0.00  0.000000    0.0

            airco  garagepl  prefarea          price
lotsize
1650     0.000000  0.000000  0.000000   45000.000000
1700     0.000000  0.000000  0.000000   27000.000000
1836     0.000000  0.000000  0.000000   32500.000000
1905     0.000000  0.000000  0.000000   62000.000000
1950     0.000000  0.000000  0.500000   40500.000000
2000     0.000000  0.000000  0.000000   38000.000000
2015     0.000000  0.000000  1.000000   55000.000000
2135     0.000000  0.000000  0.000000   50000.000000
2145     0.000000  0.166667  1.000000   51516.666667
2160     0.000000  0.000000  0.000000   44000.000000
2175     1.000000  0.000000  0.000000   61000.000000
2176     0.000000  0.000000  1.000000   55000.000000
2275     1.000000  0.000000  1.000000   52000.000000
2325     0.000000  0.000000  0.000000   60000.000000
2398     0.000000  0.000000  1.000000   44555.000000
2400     0.000000  0.000000  0.000000   27622.500000
2430     0.000000  0.000000  0.000000   38000.000000
2475     0.000000  0.000000  0.000000   34000.000000
2500     1.000000  0.000000  0.000000   47000.000000
2520     1.000000  1.000000  0.000000   53900.000000
2550     0.000000  0.000000  0.000000   65000.000000
2610     0.000000  0.000000  0.500000   54500.000000
2640     0.000000  1.000000  0.000000   40500.000000
2650     0.000000  1.000000  0.000000   40000.000000
2684     1.000000  1.000000  0.000000   46000.000000
2700     0.000000  0.000000  0.000000   44950.000000
2747     0.000000  0.000000  0.000000   60000.000000
2787     0.000000  0.000000  0.500000   47250.000000
2800     0.500000  0.500000  0.000000   54400.000000
2817     0.000000  1.000000  0.000000   78500.000000
...           ...       ...       ...            ...
8500     1.000000  2.000000  0.000000  128000.000000
8520     1.000000  2.000000  0.000000   75000.000000
8580     0.500000  2.000000  0.500000  118500.000000
8800     1.000000  2.000000  0.000000  122500.000000
8875     0.000000  1.000000  0.000000  120000.000000
8880     1.000000  1.000000  0.000000  100000.000000
8960     1.000000  3.000000  0.000000  175000.000000
9000     0.500000  1.500000  0.500000   88125.000000
9166     1.000000  2.000000  0.000000   68000.000000
9500     0.000000  3.000000  1.000000   50000.000000
9620     0.000000  2.000000  1.000000   86900.000000
9667     0.000000  1.000000  0.000000   67000.000000
9800     0.000000  2.000000  0.000000   75000.000000
9860     0.000000  0.000000  0.000000   64500.000000
9960     0.000000  2.000000  1.000000  175000.000000
10240    1.000000  2.000000  1.000000   68000.000000
10269    0.000000  1.000000  1.000000   75000.000000
10360    0.000000  1.000000  1.000000   61500.000000
10500    0.333333  1.000000  0.333333   84833.333333
10700    0.000000  0.000000  0.000000   72000.000000
11175    1.000000  1.000000  1.000000  100000.000000
11410    0.000000  0.000000  1.000000   73000.000000
11440    0.000000  1.000000  1.000000  104900.000000
11460    0.000000  2.000000  1.000000   83900.000000
12090    0.000000  2.000000  1.000000   97000.000000
12900    0.000000  2.000000  0.000000   70000.000000
12944    0.000000  0.000000  0.000000   50000.000000
13200    0.500000  1.500000  0.500000  119500.000000
15600    1.000000  2.000000  0.000000   84900.000000
16200    0.000000  0.000000  0.000000  145000.000000

[284 rows x 11 columns]

In [16]:
df_sub=df[df['lotsize']>2500]
print(df_sub)
#data frame filtering-displays the records of lotsize column greater than 2500

     lotsize  bedrooms  bathrms  stories  driveway  recroom  fullbase  gashw  \
0       5850         3        1        2         1        0         1      0
1       4000         2        1        1         1        0         0      0
2       3060         3        1        1         1        0         0      0
3       6650         3        1        2         1        1         0      0
4       6360         2        1        1         1        0         0      0
5       4160         3        1        1         1        1         1      0
6       3880         3        2        2         1        0         1      0
7       4160         3        1        3         1        0         0      0
8       4800         3        1        1         1        1         1      0
9       5500         3        2        4         1        1         0      0
10      7200         3        2        1         1        0         1      0
11      3000         2        1        1         0        0         0      0
13      2880         3        1        1         0        0         0      0
14      3600         2        1        1         1        0         0      0
15      3185         2        1        1         1        0         0      0
16      3300         3        1        2         0        0         0      0
17      5200         4        1        3         1        0         0      0
18      3450         1        1        1         1        0         0      0
19      3986         2        2        1         0        1         1      0
20      4785         3        1        2         1        1         1      0
21      4510         4        2        2         1        0         1      0
22      4000         3        1        2         1        0         0      0
23      3934         2        1        1         1        0         0      0
24      4960         2        1        1         1        0         0      0
25      3000         2        1        2         1        0         0      0
26      3800         2        1        1         1        0         0      0
27      4960         2        1        1         1        0         1      0
28      3000         3        1        1         0        0         0      0
29      4500         3        1        2         1        0         0      0
30      3500         2        1        1         0        0         1      0
..       ...       ...      ...      ...       ...      ...       ...    ...
516     6000         3        2        3         1        1         0      0
517     6000         4        2        4         1        0         0      0
518     6240         4        2        2         1        0         0      0
519     6000         3        2        2         1        1         0      0
520     7680         4        2        4         1        1         0      0
521     6000         4        2        4         1        1         0      0
522     6000         4        2        4         1        0         0      0
523     6000         4        2        4         1        0         0      0
524     6000         4        2        4         1        0         0      0
525     7475         3        2        4         1        0         0      0
526     5150         3        2        4         1        0         0      0
527     6325         3        1        4         1        0         0      0
528     6000         3        2        4         1        0         0      0
529     6000         3        2        3         1        0         0      0
530     6000         3        1        4         1        1         0      0
531     7000         3        1        4         1        0         0      0
532    12900         3        1        1         1        0         0      0
533     7686         3        1        1         1        1         1      1
534     5000         3        1        3         1        0         0      0
535     5800         3        2        4         1        0         0      0
536     6000         3        2        4         1        0         0      0
537     4800         3        1        3         1        0         0      0
538     6500         3        2        3         1        0         0      0
539     7320         4        2        2         1        0         0      0
540     6525         3        2        4         1        0         0      0
541     4800         3        2        4         1        1         0      0
542     6000         3        2        4         1        0         0      0
543     6000         3        2        4         1        1         0      0
544     6000         3        2        2         1        1         0      0
545     6000         3        1        2         1        0         0      0

     airco  garagepl  prefarea   price
0        0         1         0   42000
1        0         0         0   38500
2        0         0         0   49500
3        0         0         0   60500
4        0         0         0   61000
5        1         0         0   66000
6        0         2         0   66000
7        0         0         0   69000
8        0         0         0   83800
9        1         1         0   88500
10       1         3         0   90000
11       0         0         0   30500
13       0         0         0   36000
14       0         0         0   37000
15       1         0         0   37900
16       0         1         0   40500
17       0         0         0   40750
18       0         0         0   45000
19       0         1         0   45000
20       1         1         0   48500
21       0         0         0   65900
22       1         0         0   37900
23       0         0         0   38000
24       0         0         0   42000
25       0         0         0   42300
26       0         0         0   43500
27       1         0         0   44000
28       1         0         0   44500
29       1         0         0   44900
30       0         0         0   45000
..     ...       ...       ...     ...
516      1         0         0   95000
517      1         0         0   96500
518      1         1         0  101000
519      0         1         0  102000
520      1         1         0  103000
521      1         1         0  105000
522      1         1         0  108000
523      0         2         0  110000
524      1         1         0  113000
525      1         2         0  120000
526      1         2         0  105000
527      1         1         0  106000
528      1         1         0  107500
529      1         0         0  108000
530      1         2         0  113750
531      1         2         0  120000
532      0         2         0   70000
533      0         0         0   71000
534      1         0         0   82000
535      1         0         0   82000
536      1         0         0   82500
537      1         0         0   83000
538      1         0         0   84000
539      0         0         0   85000
540      0         1         0   85000
541      1         0         0   91500
542      1         0         0   94000
543      1         1         0  103000
544      1         1         0  105000
545      1         1         0  105000

[520 rows x 12 columns]

In [19]:
df_sub=df[df['lotsize']>2500]
print(df_sub.loc[10:40,['lotsizes','bedrooms']])
#

    lotsizes  bedrooms
10       NaN         3
11       NaN         2
13       NaN         3
14       NaN         2
15       NaN         2
16       NaN         3
17       NaN         4
18       NaN         1
19       NaN         2
20       NaN         3
21       NaN         4
22       NaN         3
23       NaN         2
24       NaN         2
25       NaN         2
26       NaN         2
27       NaN         2
28       NaN         3
29       NaN         3
30       NaN         2
31       NaN         4
32       NaN         2
33       NaN         2
34       NaN         2
35       NaN         2
36       NaN         2
37       NaN         3
38       NaN         4
39       NaN         2
40       NaN         3